config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'web/welcome#index'
  get '/admin' => 'web/admin/welcome#index'
  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
    resources :organizers, only: [ :new, :create ]
    resources :participants, only: [ :new, :create, :index ]
    resources :pages, only: :show
    namespace :admin do
      resources :organizers, except: :show
      resources :participants, except: :show
      resources :pages, except: :show
    end
  end
end

app/models/organizer.rb
class Organizer < User
  validates :first_name, presence: true,
                         human_name: true
  validates :patronymic, presence: true,
                         human_name: true
  validates :last_name, presence: true,
                        human_name: true
  validates :phone, presence: true,
                    phone: true
  validates :birth_date, presence: true
  validates :social_link, presence: true
  validates :home_adress, presence: true
  validates :experience, presence: true
  validates :reason, presence: true
  validates :activity_line, presence: true
  validates :deals, presence: true
  validates :pluses, presence: true
  validates :minuses, presence: true
  validates :accept_agreement, presence: true

  enumerize :municipality, in: Municipalities.list, default: Municipalities.list.first
  enumerize :locality, in: Localities.list, default: Localities.list.first

  include OrganizerScopes

  state_machine initial: :unviewed do
    state :unviewed
    state :confirmed
    state :banned
  end
end

app/controllers/web/admin/organizers_controller.rb
class Web::Admin::OrganizersController < Web::Admin::ApplicationController
  def index
    @organizers = Organizer.all

    respond_to do |format|
      format.html { @organizers = @organizers.decorate }
      format.xls { send_data(@organizers.confirmed.to_xls(only: [ :email, :first_name, :patronymic, :last_name, :birth_date, :phone, :social_link, :municipality, :locality, :home_adress, :experience, :reason, :activity_line, :deals, :pluses, :minuses ])) }
    end
  end

  def new
    @organizer_form = OrganizerForm.new_with_model
  end

  def create
    @organizer_form = OrganizerForm.new_with_model
    @organizer_form.submit params[:organizer]
    if @organizer_form.save
      redirect_to admin_organizers_path
    else
      render action: :new
    end
  end

  def edit
    @organizer_form = OrganizerForm.find_with_model params[:id]
  end

  def update
    @organizer_form = OrganizerForm.find_with_model params[:id]
    @organizer_form.submit params[:organizer]
    if @organizer_form.save
      redirect_to admin_organizers_path
    else
      render action: :edit
    end
  end

  def destroy
    @organizer = Organizer.find params[:id]
    @organizer.destroy
    redirect_to admin_organizers_path
  end
end

app/controllers/web/organizers_controller.rb
class Web::OrganizersController < Web::ApplicationController
  def new
    @organizer = OrganizerForm.new_with_model
  end

  def create
    @organizer = OrganizerForm.new_with_model
    @organizer.submit params[:organizer]
    if @organizer.save
      redirect_to root_path, flash: :success
    else
      render :new
    end
  end
end

app/views/web/admin/organizers/_form.html.haml
- model_class = Organizer
- current_title = page_title(action, model_class.model_name.human)
- title current_title, :admin
.page-header
  %h1=t current_title
.row
  .col-lg-12
    = render 'layouts/web/admin/shared/errors', object: @organizer_form
.row
  .col-lg-12
    = simple_form_for [:admin, @organizer_form], input_html: { class: 'form-horizontal' } do |f|
      = f.input :last_name, as: :string
      = f.input :first_name, as: :string
      = f.input :patronymic, as: :string
      = f.input :birth_date, as: :date_picker
      = f.input :phone, as: :string
      = f.input :social_link, as: :string
      = f.input :municipality
      = f.input :locality
      = f.input :home_adress, as: :string
      = f.input :experience
      = f.input :reason
      = f.input :activity_line, as: :string
      = f.input :deals
      = f.input :pluses
      = f.input :minuses
      = f.button :submit, class: 'btn-success', value: t('helpers.links.save')
      = link_to t('helpers.links.back'), admin_organizers_path, class: 'btn btn-default'

app/views/web/admin/organizers/_organizers_list.html.haml
- model_class = Organizer
%table.table.table-striped.table-condensed
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:full_name)
      %th= model_class.human_attribute_name(:place)
      %th= model_class.human_attribute_name(:created_at)
      %th=t 'helpers.links.actions'
  %tbody
    - organizers.each do |organizer|
      %tr
        %td= link_to organizer.id, edit_admin_organizer_path(organizer)
        %td= link_to organizer.full_name, edit_admin_organizer_path(organizer)
        %td= "#{organizer.municipality} #{organizer.locality}"
        %td=l organizer.created_at
        %td.actions
          - if organizer.unviewed?
            = link_to admin_organizer_path(organizer, organizer: { state: :confirmed }), method: :patch, class: 'btn btn-xs btn-success' do
              %span.glyphicon.glyphicon-ok
          = link_to edit_admin_organizer_path(organizer), class: 'btn btn-warning btn-xs' do
            %span.glyphicon.glyphicon-pencil
          = link_to admin_organizer_path(organizer), method: :delete, class: 'btn btn-xs btn-danger' do
            %span.glyphicon.glyphicon-remove

app/views/web/admin/organizers/index.html.haml
- model_class = Organizer
- title model_class.model_name.human.pluralize(:ru), :admin
.page-header
  %h1
    =t model_class.model_name.human.pluralize(:ru)
    = link_to t('helpers.links.new'), new_admin_organizer_path, class: 'btn btn-primary'
    = link_to t('helpers.download_in_format_xls'), admin_organizers_path(format: :xls), class: 'btn btn-primary'
  = render 'organizers_list', organizers: @organizers
  = link_to "#{t 'helpers.links.new'}", new_admin_organizer_path, class: 'btn btn-primary'