config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'web/welcome#index'
  get '/admin' => 'web/admin/welcome#index'
  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
    resources :organizers, only: [ :new, :create ]
    resources :participants, only: [ :new, :create, :index ]
    resources :pages, only: :show
    namespace :admin do
      resources :organizers, except: :show
      resources :participants, except: :show
      resources :pages, except: :show
    end
  end
end

app/views/web/admin/pages/_form.html.haml
- model_class = Page
- current_title = page_title(action, model_class.model_name.human)
- title current_title, :admin
.page-header
  %h1=t current_title
.row
  .col-lg-12
    = render 'layouts/web/admin/shared/errors', object: @page_form
.row
  .col-lg-12
    = simple_form_for [:admin, @page_form], input_html: { class: 'form-horizontal' } do |f|
      = f.input :title, as: :string
      = f.input :slug, as: :string
      = f.input :body
      = f.button :submit, class: 'btn-success', value: t('helpers.links.save')
      = link_to t('helpers.links.back'), admin_pages_path, class: 'btn btn-default'

app/views/web/admin/pages/_pages_list.html.haml
- model_class = Page
%table.table.table-striped.table-condensed
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:created_at)
      %th=t 'helpers.links.actions'
  %tbody
    - pages.each do |page|
      %tr
        %td= link_to page.id, edit_admin_page_path(page)
        %td= link_to page.title, edit_admin_page_path(page)
        %td=l page.created_at
        %td.actions
          = link_to edit_admin_page_path(page), class: 'btn btn-warning btn-xs' do
            %span.glyphicon.glyphicon-pencil
          = link_to admin_page_path(page), method: :delete, class: 'btn btn-xs btn-danger' do
            %span.glyphicon.glyphicon-remove

app/views/web/admin/pages/index.html.haml
- model_class = Page
- title model_class.model_name.human.pluralize(:ru), :admin
.page-header
  %h1
    =t model_class.model_name.human.pluralize(:ru)
    = link_to "#{t 'helpers.links.new'}", new_admin_page_path, class: 'btn btn-primary'
  = render 'pages_list', pages: @pages
  = link_to "#{t 'helpers.links.new'}", new_admin_page_path, class: 'btn btn-primary'