config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'web/welcome#index'
  get '/admin' => 'web/admin/welcome#index'
  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
    resources :organizers, only: [ :new, :create ]
    resources :participants, only: [ :new, :create, :index ]
    resources :pages, only: :show
    namespace :admin do
      resources :organizers, except: :show
      resources :participants, except: :show
      resources :pages, except: :show
    end
  end
end

app/models/participant.rb
require 'russia_regions'

class Participant < User
  validates :email, presence: true
  validates :first_name, presence: true,
                         human_name: true
  validates :patronymic, presence: true,
                         human_name: true
  validates :last_name, presence: true,
                        human_name: true
  validates :phone, presence: true,
                    phone: true
  validates :birth_date, presence: true
  validates :social_link, presence: true
  validates :home_adress, presence: true
  validates :reason, presence: true
  validates :activity_line, presence: true
  validates :accept_agreement, presence: true
  validates :school, presence: true
  validates :organization, presence: true
  validates :what_you_want, presence: true
  validates :block, presence: true
  validates :region, presence: true

  enumerize :municipality, in: Municipalities.list, default: Municipalities.list.first
  enumerize :locality, in: Localities.list, default: Localities.list.first
  enumerize :activity_line, in: [
                                  :assistance_to_people_with_disabilities,
                                  :development_of_voluntary_donation,
                                  :adaptation_of_children_without_parental_care,
                                  :assistance_to_the_poor,
                                  :ecology,
                                  :art_volunteering,
                                  :another
                                ]
  enumerize :block, in: [
                          :help_for_children_with_disabilities,
                          :massive_volunteering
                        ]
  include RussiaRegions

  enumerize :region, in: RussiaRegions.name_list

  include ParticipantScopes

  state_machine initial: :unviewed do
    state :unviewed
    state :confirmed
    state :banned
  end
end

app/controllers/web/admin/participants_controller.rb
class Web::Admin::ParticipantsController < Web::Admin::ApplicationController
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html { @participants = @participants.decorate }
      format.xls { send_data(@participants.all.to_xls(only: [ :email, :first_name, :patronymic, :last_name, :phone, :birth_date, :social_link, :home_adress, :reason, :activity_line, :school, :organization, :what_you_want, :block, :another_line ])) }
    end
  end

  def new
    @participant_form = ParticipantForm.new_with_model
  end

  def create
    @participant_form = ParticipantForm.new_with_model
    @participant_form.submit params[:participant]
    if @participant_form.save
      redirect_to admin_participants_path
    else
      render action: :new
    end
  end

  def edit
    @participant_form = ParticipantForm.find_with_model params[:id]
  end

  def update
    @participant_form = ParticipantForm.find_with_model params[:id]
    @participant_form.submit params[:participant]
    if @participant_form.save
      redirect_to admin_participants_path
    else
      render action: :edit
    end
  end

  def destroy
    @participant = Participant.find params[:id]
    @participant.destroy
    redirect_to admin_participants_path
  end
end

app/controllers/web/participants_controller.rb
class Web::ParticipantsController < Web::ApplicationController
  def index
    @participants = {}
    @participants[:confirmed] = Participant.confirmed.decorate
    @participants[:unviewed] = Participant.unviewed.decorate
    @participants[:banned] = Participant.banned.decorate
  end

  def new
    @participant = ParticipantForm.new_with_model
  end

  def create
    @participant = ParticipantForm.new_with_model
    @participant.submit params[:participant]
    if @participant.save
      redirect_to root_path, flash: :success
    else
      render :new
    end
  end
end

app/views/web/admin/participants/_form.html.haml
- model_class = Participant
- current_title = page_title(action, model_class.model_name.human)
- title current_title, :admin
.page-header
  %h1=t current_title
.row
  .col-lg-12
    = render 'layouts/web/admin/shared/errors', object: @participant_form
.row
  .col-lg-12
    = simple_form_for [:admin, @participant_form], input_html: { class: 'form-horizontal' } do |f|
      = f.input :last_name, as: :string
      = f.input :first_name, as: :string
      = f.input :patronymic, as: :string
      = f.input :birth_date, as: :date_picker
      = f.input :phone, as: :string
      = f.input :social_link, as: :string
      = f.input :region
      = f.input :municipality
      = f.input :locality
      = f.input :home_adress, as: :string
      = f.input :social_link, as: :string, placeholder: t('activerecord.attributes.participant.social_link'), label: false
      = f.input :email, as: :string, placeholder: t('activerecord.attributes.participant.email'), label: false
      = f.input :school, as: :string, placeholder: t('activerecord.attributes.participant.school'), label: false
      = f.input :reason
      = f.input :activity_line, as: :select, collection: enumerize_locales_hash(Participant, :activity_line)
      = f.input :another_line, as: :string, placeholder: t('activerecord.attributes.participant.another_line'), label: false
      = f.input :organization, placeholder: t('activerecord.attributes.participant.organization'), label: false
      = f.input :what_you_want, placeholder: t('activerecord.attributes.participant.what_you_want'), label: false
      = f.input :block, placeholder: t('activerecord.attributes.participant.block')
      = f.input :accept_agreement, as: :boolean
      = f.button :submit, class: 'btn-success', value: t('helpers.links.save')
      = link_to t('helpers.links.back'), admin_participants_path, class: 'btn btn-default'

app/views/web/admin/participants/_participants_list.html.haml
- model_class = Participant
%table.table.table-striped.table-condensed
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:full_name)
      %th= model_class.human_attribute_name(:place)
      %th= model_class.human_attribute_name(:created_at)
      %th=t 'helpers.links.actions'
  %tbody
    - participants.each do |participant|
      %tr
        %td= link_to participant.id, edit_admin_participant_path(participant)
        %td= link_to participant.full_name, edit_admin_participant_path(participant)
        %td= participant.place
        %td=l participant.created_at
        %td.actions
          - if participant.unviewed?
            = link_to admin_participant_path(participant, participant: { state: :confirmed }), method: :patch, class: 'btn btn-xs btn-success' do
              %span.glyphicon.glyphicon-ok
          = link_to edit_admin_participant_path(participant), class: 'btn btn-warning btn-xs' do
            %span.glyphicon.glyphicon-pencil
          = link_to admin_participant_path(participant), method: :delete, class: 'btn btn-xs btn-danger' do
            %span.glyphicon.glyphicon-remove

app/views/web/admin/participants/edit.html.haml
= render partial: 'form', locals: { action: :update }

app/views/web/admin/participants/index.html.haml
- model_class = Participant
- title model_class.model_name.human.pluralize(:ru), :admin
.page-header
  %h1
    =t model_class.model_name.human.pluralize(:ru)
    = link_to "#{t 'helpers.links.new'}", new_admin_participant_path, class: 'btn btn-primary'
    = link_to t('helpers.download_in_format_xls'), admin_participants_path(format: :xls), class: 'btn btn-primary'
  = render 'participants_list', participants: @participants
  = link_to "#{t 'helpers.links.new'}", new_admin_participant_path, class: 'btn btn-primary'

app/views/web/admin/participants/new.html.haml
= render partial: 'form', locals: { action: :create }