config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'web/welcome#index'
  get '/admin' => 'web/admin/welcome#index'
  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
    resources :organizers, only: [ :new, :create ]
    resources :participants, only: [ :new, :create, :index ]
    resources :pages, only: :show
    namespace :admin do
      resources :organizers, except: :show
      resources :participants, except: :show
      resources :pages, except: :show
    end
  end
end

app/views/layouts/web/admin/_navbar.html.haml
%header.navbar.navbar-default
  .navbar-header
    %button.navbar-toggle{ type: :button, data: { toggle: :collapse, target: '.navbar-collapse' } }
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: root_path }
      = t('application.name')
  .navbar-collapse.collapse
    %ul.nav.navbar-nav
      = menu_item admin_organizers_path do
        = "#{Organizer.model_name.human.pluralize(:ru)} / #{@organizers_count}"
      = menu_item admin_participants_path do
        = "#{Participant.model_name.human.pluralize(:ru)} / #{@participants_count}"
      = menu_item admin_pages_path do
        = Page.model_name.human.pluralize(:ru)
    %ul.nav.navbar-nav.navbar-right

app/views/layouts/web/admin/application.html.haml
%html
  %head
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'web/admin/application', "web/admin/#{controller_name}"
    = javascript_include_tag 'web/admin/application', "web/admin/#{controller_name}"
    = csrf_meta_tags
    %title
      = yield :title
  %body
    = render 'layouts/web/admin/navbar'
    .container
      = yield